name: Validate, Build, and Upload Artifact to S3

on:
  workflow_call:
    inputs:
      AWS_REGION:
        description: The AWS region
        type: string
        default: eu-west-2
      GENERATE_OPEN_PROXY_API_SPEC:
        description: Whether open proxy API spec needs to be generated
        type: string
        default: false
      TEMPLATE_NAME:
        description: The name of the SAM template to upload
        type: string
        default: template.yaml
      WORKING_DIRECTORY:
        description: Path to working directory in repo
        required: true
        type: string
    secrets:
      ARTIFACT_BUCKET:
        description: Artifact source bucket for Read ID Mock SAM artifact
        required: true
      GH_ACTIONS_ROLE_ARN:
        description: AWS role for pushing the test image and AWS artifact to AWS
        required: true
      SIGNING_PROFILE_NAME:
        description: Profile used to sign SAM artifact
        required: true

jobs:
  upload-artifact:
    name: "Validate and Upload Artifact"
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    env:
      SAM_CLI_TELEMETRY: 0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          cache: npm
          cache-dependency-path: ${{ inputs.WORKING_DIRECTORY }}/package-lock.json
          node-version-file: ${{ inputs.WORKING_DIRECTORY }}/.nvmrc

      - name: Configure Authentication for Private Packages in .npmrc
        if: inputs.GENERATE_OPEN_PROXY_API_SPEC == 'true'
        run: |
          echo 'engine-strict=true' > .npmrc
          echo 'ignore-scripts=true' >> .npmrc
          echo '@govuk-one-login:registry=https://npm.pkg.github.com/' >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> .npmrc

      - name: Install Dependencies
        if: inputs.GENERATE_OPEN_PROXY_API_SPEC == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm clean-install

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 #v5.1.1
        with:
          aws-region: ${{ inputs.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}

      - name: Generate Proxy OpenAPI Spec
        if: inputs.GENERATE_OPEN_PROXY_API_SPEC == 'true'
        run: |
          npm run generate-proxy-open-api

      - name: SAM Validate
        run: sam validate --lint --template ${{ inputs.TEMPLATE_NAME }}

      - name: SAM Build
        run: sam build --cached --template ${{ inputs.TEMPLATE_NAME }}

      - name: Upload SAM Artifact into the Artifact Bucket
        uses: govuk-one-login/devplatform-upload-action@v3.11.0
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          template-file: .aws-sam/build/template.yaml
          working-directory: ${{ inputs.WORKING_DIRECTORY }}
